SELECT 9 as HOUR, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATETIME like '___________09%'
union
SELECT 10, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATETIME like '___________10%'
union
SELECT 11, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATETIME like '___________11%'
union
SELECT 12, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATETIME like '___________12%'
union
SELECT 13, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATETIME like '___________13%'
union
SELECT 14, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATETIME like '___________14%'
union
SELECT 15, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATETIME like '___________15%'
union
SELECT 16, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATETIME like '___________16%'
union
SELECT 17, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATETIME like '___________17%'
union
SELECT 18, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATETIME like '___________18%'
union
SELECT 19, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATETIME like '___________19%'
